using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class RaceModel
{
    [RealtimeProperty(1, true, true)]
    private double _gameStartTime;
}


/* ----- Begin Normal Autogenerated Code ----- */
public partial class RaceModel : RealtimeModel {
    public double gameStartTime {
        get {
            return _cache.LookForValueInCache(_gameStartTime, entry => entry.gameStartTimeSet, entry => entry.gameStartTime);
        }
        set {
            if (this.gameStartTime == value) return;
            _cache.UpdateLocalCache(entry => { entry.gameStartTimeSet = true; entry.gameStartTime = value; return entry; });
            InvalidateReliableLength();
            FireGameStartTimeDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(RaceModel model, T value);
    public event PropertyChangedHandler<double> gameStartTimeDidChange;
    
    private struct LocalCacheEntry {
        public bool gameStartTimeSet;
        public double gameStartTime;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        GameStartTime = 1,
    }
    
    public RaceModel() : this(null) {
    }
    
    public RaceModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireGameStartTimeDidChange(double value) {
        try {
            gameStartTimeDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteDoubleLength((uint)PropertyID.GameStartTime);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.gameStartTimeSet) {
                length += WriteStream.WriteDoubleLength((uint)PropertyID.GameStartTime);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteDouble((uint)PropertyID.GameStartTime, _gameStartTime);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.gameStartTimeSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.gameStartTimeSet) {
                stream.WriteDouble((uint)PropertyID.GameStartTime, entry.gameStartTime);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.GameStartTime: {
                    double previousValue = _gameStartTime;
                    _gameStartTime = stream.ReadDouble();
                    bool gameStartTimeExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.gameStartTimeSet);
                    if (!gameStartTimeExistsInChangeCache && _gameStartTime != previousValue) {
                        FireGameStartTimeDidChange(_gameStartTime);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _gameStartTime = gameStartTime;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
