using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TruckModel
{
    [RealtimeProperty(1, true, true)] private int _owner;
    [RealtimeProperty(2, true, true)] private float _health;
    [RealtimeProperty(3, true, true)] private Vector3 _explosionPoint;
    [RealtimeProperty(4, true, true)] private bool _isBoombastic;
    [RealtimeProperty(5, true, true)] private float _maxHealth;
}


/* ----- Begin Normal Autogenerated Code ----- */
public partial class TruckModel : RealtimeModel {
    public int owner {
        get {
            return _cache.LookForValueInCache(_owner, entry => entry.ownerSet, entry => entry.owner);
        }
        set {
            if (this.owner == value) return;
            _cache.UpdateLocalCache(entry => { entry.ownerSet = true; entry.owner = value; return entry; });
            InvalidateReliableLength();
            FireOwnerDidChange(value);
        }
    }
    
    public float health {
        get {
            return _cache.LookForValueInCache(_health, entry => entry.healthSet, entry => entry.health);
        }
        set {
            if (this.health == value) return;
            _cache.UpdateLocalCache(entry => { entry.healthSet = true; entry.health = value; return entry; });
            InvalidateReliableLength();
            FireHealthDidChange(value);
        }
    }
    
    public UnityEngine.Vector3 explosionPoint {
        get {
            return _cache.LookForValueInCache(_explosionPoint, entry => entry.explosionPointSet, entry => entry.explosionPoint);
        }
        set {
            if (this.explosionPoint == value) return;
            _cache.UpdateLocalCache(entry => { entry.explosionPointSet = true; entry.explosionPoint = value; return entry; });
            InvalidateReliableLength();
            FireExplosionPointDidChange(value);
        }
    }
    
    public bool isBoombastic {
        get {
            return _cache.LookForValueInCache(_isBoombastic, entry => entry.isBoombasticSet, entry => entry.isBoombastic);
        }
        set {
            if (this.isBoombastic == value) return;
            _cache.UpdateLocalCache(entry => { entry.isBoombasticSet = true; entry.isBoombastic = value; return entry; });
            InvalidateReliableLength();
            FireIsBoombasticDidChange(value);
        }
    }
    
    public float maxHealth {
        get {
            return _cache.LookForValueInCache(_maxHealth, entry => entry.maxHealthSet, entry => entry.maxHealth);
        }
        set {
            if (this.maxHealth == value) return;
            _cache.UpdateLocalCache(entry => { entry.maxHealthSet = true; entry.maxHealth = value; return entry; });
            InvalidateReliableLength();
            FireMaxHealthDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TruckModel model, T value);
    public event PropertyChangedHandler<int> ownerDidChange;
    public event PropertyChangedHandler<float> healthDidChange;
    public event PropertyChangedHandler<UnityEngine.Vector3> explosionPointDidChange;
    public event PropertyChangedHandler<bool> isBoombasticDidChange;
    public event PropertyChangedHandler<float> maxHealthDidChange;
    
    private struct LocalCacheEntry {
        public bool ownerSet;
        public int owner;
        public bool healthSet;
        public float health;
        public bool explosionPointSet;
        public UnityEngine.Vector3 explosionPoint;
        public bool isBoombasticSet;
        public bool isBoombastic;
        public bool maxHealthSet;
        public float maxHealth;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        Owner = 1,
        Health = 2,
        ExplosionPoint = 3,
        IsBoombastic = 4,
        MaxHealth = 5,
    }
    
    public TruckModel() : this(null) {
    }
    
    public TruckModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireOwnerDidChange(int value) {
        try {
            ownerDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireHealthDidChange(float value) {
        try {
            healthDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireExplosionPointDidChange(UnityEngine.Vector3 value) {
        try {
            explosionPointDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireIsBoombasticDidChange(bool value) {
        try {
            isBoombasticDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireMaxHealthDidChange(float value) {
        try {
            maxHealthDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Owner, (uint)_owner);
            length += WriteStream.WriteFloatLength((uint)PropertyID.Health);
            length += WriteStream.WriteBytesLength((uint)PropertyID.ExplosionPoint, WriteStream.Vector3ToBytesLength());
            length += WriteStream.WriteVarint32Length((uint)PropertyID.IsBoombastic, _isBoombastic ? 1u : 0u);
            length += WriteStream.WriteFloatLength((uint)PropertyID.MaxHealth);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.ownerSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.Owner, (uint)entry.owner);
            }
            if (entry.healthSet) {
                length += WriteStream.WriteFloatLength((uint)PropertyID.Health);
            }
            if (entry.explosionPointSet) {
                length += WriteStream.WriteBytesLength((uint)PropertyID.ExplosionPoint, WriteStream.Vector3ToBytesLength());
            }
            if (entry.isBoombasticSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.IsBoombastic, entry.isBoombastic ? 1u : 0u);
            }
            if (entry.maxHealthSet) {
                length += WriteStream.WriteFloatLength((uint)PropertyID.MaxHealth);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.Owner, (uint)_owner);
            stream.WriteFloat((uint)PropertyID.Health, _health);
            stream.WriteBytes((uint)PropertyID.ExplosionPoint, WriteStream.Vector3ToBytes(_explosionPoint));
            stream.WriteVarint32((uint)PropertyID.IsBoombastic, _isBoombastic ? 1u : 0u);
            stream.WriteFloat((uint)PropertyID.MaxHealth, _maxHealth);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.ownerSet || entry.healthSet || entry.explosionPointSet || entry.isBoombasticSet || entry.maxHealthSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.ownerSet) {
                stream.WriteVarint32((uint)PropertyID.Owner, (uint)entry.owner);
                didWriteProperties = true;
            }
            if (entry.healthSet) {
                stream.WriteFloat((uint)PropertyID.Health, entry.health);
                didWriteProperties = true;
            }
            if (entry.explosionPointSet) {
                stream.WriteBytes((uint)PropertyID.ExplosionPoint, WriteStream.Vector3ToBytes(entry.explosionPoint));
                didWriteProperties = true;
            }
            if (entry.isBoombasticSet) {
                stream.WriteVarint32((uint)PropertyID.IsBoombastic, entry.isBoombastic ? 1u : 0u);
                didWriteProperties = true;
            }
            if (entry.maxHealthSet) {
                stream.WriteFloat((uint)PropertyID.MaxHealth, entry.maxHealth);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Owner: {
                    int previousValue = _owner;
                    _owner = (int)stream.ReadVarint32();
                    bool ownerExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.ownerSet);
                    if (!ownerExistsInChangeCache && _owner != previousValue) {
                        FireOwnerDidChange(_owner);
                    }
                    break;
                }
                case (uint)PropertyID.Health: {
                    float previousValue = _health;
                    _health = stream.ReadFloat();
                    bool healthExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.healthSet);
                    if (!healthExistsInChangeCache && _health != previousValue) {
                        FireHealthDidChange(_health);
                    }
                    break;
                }
                case (uint)PropertyID.ExplosionPoint: {
                    UnityEngine.Vector3 previousValue = _explosionPoint;
                    _explosionPoint = ReadStream.Vector3FromBytes(stream.ReadBytes());
                    bool explosionPointExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.explosionPointSet);
                    if (!explosionPointExistsInChangeCache && _explosionPoint != previousValue) {
                        FireExplosionPointDidChange(_explosionPoint);
                    }
                    break;
                }
                case (uint)PropertyID.IsBoombastic: {
                    bool previousValue = _isBoombastic;
                    _isBoombastic = (stream.ReadVarint32() != 0);
                    bool isBoombasticExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.isBoombasticSet);
                    if (!isBoombasticExistsInChangeCache && _isBoombastic != previousValue) {
                        FireIsBoombasticDidChange(_isBoombastic);
                    }
                    break;
                }
                case (uint)PropertyID.MaxHealth: {
                    float previousValue = _maxHealth;
                    _maxHealth = stream.ReadFloat();
                    bool maxHealthExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.maxHealthSet);
                    if (!maxHealthExistsInChangeCache && _maxHealth != previousValue) {
                        FireMaxHealthDidChange(_maxHealth);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _owner = owner;
        _health = health;
        _explosionPoint = explosionPoint;
        _isBoombastic = isBoombastic;
        _maxHealth = maxHealth;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
